### PR TITLE
Add missing taxranks that appear in NCBI Taxonomy Database

### LINKED ISSUE #4: Add a term for "strain"
There has been a request to add "strain" to NCBITaxon: 

- https://github.com/obophenotype/ncbitaxon/issues/107

I think the OBO NCBITaxon rendering should utilize URIs from taxrank

- https://github.com/obophenotype/ncbitaxon/issues/97

Is this in scope for taxrank?

### PR DESCRIPTION
**Pull request by cthoyt**
Closes #4 

This PR adds the ranks that appear in the NCBI Taxonomy Database to TAXRANK. Here's a table that shows the impact of each of these terms, where the count is how many distinct NCBI Taxa have this rank. I then ran `make` and `make prepare_release` after.

Note: I also did a bit of housekeeping in this PR too to add the license and contributor list.

| NCBI Rank       | CURIE                     |   Count | Example           | Example Name                             |
|-----------------|---------------------------|---------|-------------------|------------------------------------------|
| strain          | NCBITaxon:strain          |   46478 | NCBITaxon:355     | Azotobacter chroococcum (strain mcd 1)   |
| isolate         | NCBITaxon:isolate         |    1305 | NCBITaxon:5838    | Plasmodium falciparum FCR-3/Gambia       |
| serotype        | NCBITaxon:serotype        |    1229 | NCBITaxon:10510   | Bovine adenovirus 3                      |
| clade           | NCBITaxon:clade           |     963 | NCBITaxon:3193    | Embryophyta                              |
| forma specialis | NCBITaxon:forma_specialis |     785 | NCBITaxon:5508    | Fusarium oxysporum f. sp. cucumerinum    |
| serogroup       | NCBITaxon:serogroup       |     154 | NCBITaxon:491     | Neisseria meningitidis serogroup B       |
| genotype        | NCBITaxon:genotype        |      22 | NCBITaxon:33745   | Hepatitis C virus genotype 4             |
| biotype         | NCBITaxon:biotype         |      17 | NCBITaxon:725     | Haemophilus influenzae biotype aegyptius |
| morph           | NCBITaxon:morph           |      11 | NCBITaxon:304407  | Acontias orientalis morph lineacauda     |
| cohort          | NCBITaxon:cohort          |       5 | NCBITaxon:33341   | Polyneoptera                             |
| pathogroup      | NCBITaxon:pathogroup      |       5 | NCBITaxon:1982676 | Xanthomonas axonopodis subcluster 9.1    |
| subcohort       | NCBITaxon:subcohort       |       3 | NCBITaxon:32519   | Ostariophysi                             |

### CODE REVIEW

**Comment by cmungall** [comment]
LGTM

**Review by hlapp — APPROVED** [review]
Nice 👍

**Comment by hlapp** [comment]
@cthoyt any chance you can add the OWL conversion?

**Comment by cthoyt** [comment]
@hlapp I ran `make` and `make_release` as instructed in the README-editors file and committed the two updated files in [0527d24](https://github.com/phenoscape/taxrank/pull/5/commits/0527d24345316b38d1167dc95b7f7ced80a74072). Since this repository doesn't have contributing guidelines, I wasn't sure if this was something I should do or not

**Review by hlapp — APPROVED** [review]
Awesome, thanks so much @cthoyt. I agree there should be a contributors template. I'll make that an issue so it can be tracked.

**Comment by hlapp** [comment]
@balhoff are you handling new release etc?

**Comment by balhoff** [comment]
@hlapp sure I can do that!

**Pull request merged**
